version: '3.9'

networks:
  default:
    name: golang-reference-project

services:
  app:
    image: ghcr.io/valentinlutz/golang-reference-project:latest
    container_name: app
    hostname: app
    volumes:
      - ../../config/config.none-container.yaml:/app/config/config.yaml:ro
      - ../../config/none-dev.crt:/app/config/cert.crt:ro
      - ../../config/none-dev.key:/app/config/cert.key:ro
    ports:
      - '9090:8080'